import type { AnalysisService } from "./types";

export const MOCK_SERVICES: AnalysisService[] = [
  {
    id: "hgb",
    keyword: "HGB",
    service: "Haemoglobin",
    category: "Haematology",
    method: "Cyanmethaemoglobin",
    instrument: "Sysmex XN",
    unit: "g/dL",
    normalRangeM: "13.0–17.0",
    normalRangeF: "12.0–16.0",
    tat: "2h",
    price: "₹150",
  },
  {
    id: "wbc",
    keyword: "WBC",
    service: "WBC Count",
    category: "Haematology",
    method: "Impedance",
    instrument: "Sysmex XN",
    unit: "x10³/µL",
    normalRangeM: "4.0–10.0",
    normalRangeF: "4.0–10.0",
    tat: "2h",
    price: "₹200",
  },
  {
    id: "gluc",
    keyword: "GLUC",
    service: "Glucose (Random)",
    category: "Biochemistry",
    method: "GOD–POD",
    instrument: "Cobas 6000",
    unit: "mg/dL",
    normalRangeM: "70–200",
    normalRangeF: "70–200",
    tat: "2h",
    price: "₹80",
  },
  {
    id: "hba1c",
    keyword: "HBA1C",
    service: "Glycated Haemoglobin",
    category: "Biochemistry",
    method: "HPLC",
    instrument: "Bio-Rad D10",
    unit: "%",
    normalRangeM: "<5.7%",
    normalRangeF: "<5.7%",
    tat: "4h",
    price: "₹600",
  },
  {
    id: "tsh",
    keyword: "TSH",
    service: "Thyroid Stimulating Hormone",
    category: "Serology",
    method: "CLIA",
    instrument: "Cobas e411",
    unit: "mIU/L",
    normalRangeM: "0.4–4.0",
    normalRangeF: "0.4–4.0",
    tat: "4h",
    price: "₹450",
  },
];

export const CATEGORIES = [
  "All",
  "Haematology",
  "Biochemistry",
  "Microbiology",
  "Serology",
  "Histopathology",
];
