import type { Department } from "./types";

export const DEPT_CONFIG: Record<
  string,
  { iconBg: string; iconBorder: string; iconColor: string }
> = {
  blood: { iconBg: "#FFF1F2", iconBorder: "#FECDD3", iconColor: "#9F1239" },
  bio: { iconBg: "#EEF2FF", iconBorder: "#C7D2FE", iconColor: "#4338CA" },
  micro: { iconBg: "#F0FDFA", iconBorder: "#99F6E4", iconColor: "#0F766E" },
  serology: { iconBg: "#FDF4FF", iconBorder: "#E9D5FF", iconColor: "#7E22CE" },
  histo: { iconBg: "#FFFBEB", iconBorder: "#FDE68A", iconColor: "#92400E" },
  cyto: { iconBg: "#F0F9FF", iconBorder: "#BAE6FD", iconColor: "#075985" },
  molec: { iconBg: "#F1F5F9", iconBorder: "#CBD5E1", iconColor: "#475569" },
};

export const DUMMY_DATA: Department[] = [
  {
    id: "1",
    name: "Haematology",
    shortCode: "HAEM",
    head: "Dr. Rajesh Kumar",
    analysts: "M. Joseph, S. Pillai",
    instruments: "Sysmex XN-1000",
    tatTarget: "2 hrs",
    testsToday: 82,
    tatCompliance: 88,
    status: "Active",
    iconType: "blood",
  },
  {
    id: "2",
    name: "Biochemistry",
    shortCode: "BIO",
    head: "Dr. Priya Mehta",
    analysts: "R. Sharma, K. Joseph",
    instruments: "Cobas 6000, D-10",
    tatTarget: "4 hrs",
    testsToday: 115,
    tatCompliance: 74,
    status: "Active",
    iconType: "bio",
  },
  {
    id: "3",
    name: "Microbiology",
    shortCode: "MICRO",
    head: "Dr. A. Nair",
    analysts: "K. Joseph",
    instruments: "BD BACTEC FX",
    tatTarget: "48 hrs",
    testsToday: 18,
    tatCompliance: 35,
    status: "Active",
    iconType: "micro",
  },
  {
    id: "4",
    name: "Serology / Immunology",
    shortCode: "SER",
    head: "Dr. S. Verma",
    analysts: "A. Nair, R. Sharma",
    instruments: "Abbott Architect",
    tatTarget: "6 hrs",
    testsToday: 44,
    tatCompliance: 92,
    status: "Active",
    iconType: "serology",
  },
  {
    id: "5",
    name: "Histopathology",
    shortCode: "HISTO",
    head: "Dr. M. Iyer",
    analysts: "P. Kumar",
    instruments: "Leica Autostainer",
    tatTarget: "72 hrs",
    testsToday: 9,
    tatCompliance: 55,
    status: "Active",
    iconType: "histo",
  },
  {
    id: "6",
    name: "Cytology",
    shortCode: "CYTO",
    head: "Dr. M. Iyer",
    analysts: "P. Kumar, S. Das",
    instruments: "Olympus BX53",
    tatTarget: "48 hrs",
    testsToday: 12,
    tatCompliance: 68,
    status: "Active",
    iconType: "cyto",
  },
  {
    id: "7",
    name: "Molecular Biology",
    shortCode: "MOL",
    head: "Not assigned",
    analysts: "Not assigned",
    instruments: "Pending setup",
    tatTarget: "—",
    testsToday: 0,
    tatCompliance: 0,
    status: "Inactive",
    iconType: "molec",
  },
];
