import type { CommonTabItem } from "@/src/ui/components/molecules/CommonTabs";
import type { ValidatedMethod } from "./types";

export const METHOD_TABS: CommonTabItem[] = [
  { id: "All", label: "All" },
  { id: "Haematology", label: "Haematology" },
  { id: "Biochemistry", label: "Biochemistry" },
  { id: "Microbiology", label: "Microbiology" },
];

export const DUMMY_DATA: ValidatedMethod[] = [
  {
    id: "1",
    name: "Cyanmethaemoglobin",
    linkedAnalysis: "HGB",
    principle: "Photometric",
    instrument: "Sysmex XN-1000",
    standard: "ICSH",
    department: "Haematology",
    validatedOn: "12 Jan 2025",
    status: "Active",
  },
  {
    id: "2",
    name: "Electrical Impedance",
    linkedAnalysis: "WBC, PLT, RBC",
    principle: "Impedance",
    instrument: "Sysmex XN-1000",
    standard: "CLSI H20",
    department: "Haematology",
    validatedOn: "12 Jan 2025",
    status: "Active",
  },
  {
    id: "3",
    name: "GOD-POD Enzymatic",
    linkedAnalysis: "Glucose",
    principle: "Enzymatic Colorimetric",
    instrument: "Roche Cobas 6000",
    standard: "IFCC",
    department: "Biochemistry",
    validatedOn: "05 Feb 2025",
    status: "Active",
  },
  {
    id: "4",
    name: "Ion Selective Electrode",
    linkedAnalysis: "Na+, K+, Cl-",
    principle: "Potentiometry (ISE)",
    instrument: "Roche Cobas 6000",
    standard: "CLSI EP9",
    department: "Biochemistry",
    validatedOn: "05 Feb 2025",
    status: "Active",
  },
  {
    id: "5",
    name: "HPLC Ion Exchange",
    linkedAnalysis: "HbA1c",
    principle: "Chromatography",
    instrument: "Bio-Rad D-10",
    standard: "NGSP / IFCC",
    department: "Biochemistry",
    validatedOn: "18 Mar 2025",
    status: "Active",
  },
  {
    id: "6",
    name: "Automated Blood Culture",
    linkedAnalysis: "Blood Culture",
    principle: "Continuous Monitoring",
    instrument: "BD BACTEC FX",
    standard: "CLSI M47",
    department: "Microbiology",
    validatedOn: "22 Nov 2024",
    status: "Active",
  },
  {
    id: "7",
    name: "Homogeneous Enzymatic",
    linkedAnalysis: "LDL, HDL, TC, TG",
    principle: "Enzymatic Colorimetric",
    instrument: "Roche Cobas 6000",
    standard: "CDC NHLBI",
    department: "Biochemistry",
    validatedOn: "05 Feb 2025",
    status: "Inactive",
  },
];
