import {
  CorporateFare as DeptIcon,
  Star as StarIcon,
  TrackChanges as ProfileIcon,
  Biotech as TestIcon,
} from "@mui/icons-material";
import type { AnalysisProfile } from "./types";

export const DUMMY_PROFILES: AnalysisProfile[] = [
  {
    id: "1",
    name: "Cardiac Markers",
    department: "Biochemistry",
    analytesCount: 6,
    analytesList: "Troponin I, Troponin T, CK-MB, LDH +2 more",
    sampleType: "Blood",
    container: "SST (Yellow)",
    tat: "1h",
    price: "₹2,800",
    monthlyUsage: 23,
    maxUsage: 130,
  },
  {
    id: "2",
    name: "CBC Complete",
    department: "Haematology",
    analytesCount: 18,
    analytesList: "HGB, WBC, RBC, PLT +14 more",
    sampleType: "Blood",
    container: "EDTA (Purple)",
    tat: "2h",
    price: "₹350",
    monthlyUsage: 128,
    maxUsage: 130,
  },
  {
    id: "3",
    name: "Diabetic Monitoring Panel",
    department: "Biochemistry",
    analytesCount: 6,
    analytesList:
      "Fasting Glucose, Post-Prandial Glucose, HbA1c, Fructosamine +2 more",
    sampleType: "Blood",
    container: "Fluoride (Grey)",
    tat: "4h",
    price: "₹1,100",
    monthlyUsage: 48,
    maxUsage: 130,
  },
  {
    id: "4",
    name: "LFT Panel",
    department: "Biochemistry",
    analytesCount: 10,
    analytesList: "Total Bilirubin, Direct Bilirubin, SGOT, SGPT +6 more",
    sampleType: "Blood",
    container: "SST (Yellow)",
    tat: "3h",
    price: "₹700",
    monthlyUsage: 84,
    maxUsage: 130,
  },
  {
    id: "5",
    name: "Lipid Profile",
    department: "Biochemistry",
    analytesCount: 6,
    analytesList: "Total Cholesterol, HDL, LDL, VLDL +2 more",
    sampleType: "Blood",
    container: "SST (Yellow)",
    tat: "4h",
    price: "₹800",
    monthlyUsage: 72,
    maxUsage: 130,
  },
  {
    id: "6",
    name: "RFT Panel",
    department: "Biochemistry",
    analytesCount: 6,
    analytesList: "Urea, Creatinine, eGFR, Uric Acid +2 more",
    sampleType: "Blood",
    container: "SST (Yellow)",
    tat: "3h",
    price: "₹650",
    monthlyUsage: 55,
    maxUsage: 130,
  },
  {
    id: "7",
    name: "Thyroid Profile",
    department: "Serology",
    analytesCount: 4,
    analytesList: "TSH, T3, T4, Free T4 (FT4)",
    sampleType: "Blood",
    container: "SST (Yellow)",
    tat: "4h",
    price: "₹1,200",
    monthlyUsage: 61,
    maxUsage: 130,
  },
  {
    id: "8",
    name: "Urine Routine & Microscopy",
    department: "Microbiology",
    analytesCount: 14,
    analytesList: "Colour, Clarity, pH, Specific Gravity +10 more",
    sampleType: "Urine",
    container: "Universal (White)",
    tat: "1h",
    price: "₹200",
    monthlyUsage: 93,
    maxUsage: 130,
  },
];

export const PROFILE_TABS = [
  { id: "All", label: "All" },
  { id: "Haematology", label: "Haematology" },
  { id: "Biochemistry", label: "Biochemistry" },
  { id: "Serology", label: "Serology" },
  { id: "Microbiology", label: "Microbiology" },
];

export const PROFILE_STATS = [
  {
    label: "Total Profiles",
    value: "8",
    subtitle: "Active bundles",
    tone: "primary" as const,
    icon: <ProfileIcon />,
  },
  {
    label: "Most Used",
    value: "CBC Complete",
    subtitle: "This month",
    tone: "warning" as const,
    icon: <StarIcon />,
  },
  {
    label: "Departments",
    value: "4",
    subtitle: "Covered",
    tone: "info" as const,
    icon: <DeptIcon />,
  },
  {
    label: "Total Tests",
    value: "70",
    subtitle: "Across all profiles",
    tone: "success" as const,
    icon: <TestIcon />,
  },
];
